[pytest]
minversion = 7.0
addopts = -ra
pythonpath = app
# Limitar descubrimiento de tests sólo a carpeta tests del proyecto
testpaths = tests
# Evitar recolectar tests de paquetes vendor dentro de Lib/site-packages
norecursedirs = Lib site-packages .* build dist
